[project]
name = "glatzel-bench"
channels = ["conda-forge", "pytorch"]
platforms = ["win-64"]
authors = ["Glatzel <893016099@qq.com>"]

[dependencies]
python = "*"
numpy = "1.26.*"
pygal = "*"
pytest = "*"
pytest-benchmark = "*"
numba = ">=0.60.0"
pyfftw = "*"
pytorch = { version = "*", build = "*cpu*" }
scipy = "*"
torchaudio = "*"

[pypi-dependencies]
pygaljs = "*"
audiofile = "*"
librosa = "*"
soundfile = "*"
ssqueezepy = "*"

