[project]
name = "glatzel-bench"
channels = ["conda-forge", "pytorch"]
platforms = ["win-64"]
authors = ["Glatzel <893016099@qq.com>"]

[feature.base.dependencies]
python = "3.11.*"
numpy = "1.24.*"
pytest = "*"
pytest-benchmark = "*"
pytest-cov = "*"

[feature.audio.dependencies]
librosa = "*"
numba = ">=0.60.0"
pyfftw = "*"
pygal = "*"
pysoundfile = "*"
scipy = "*"
torchaudio = "*"
numexpr = "*"
[feature.audio.pypi-dependencies]
torch = { url = "https://github.com/Glatzel/torch-minimal/releases/download/v2.5.1/torch-2.5.1-cp311-cp311-win_amd64.whl" }
audiofile = "*"
ssqueezepy = "*"

[feature.arithmetic.dependencies]
numba = ">=0.60.0"
numexpr = "*"
pyfftw = "*"
pygal = "*"
scipy = "*"
[feature.arithmetic.pypi-dependencies]
torch = { url = "https://github.com/Glatzel/torch-minimal/releases/download/v2.5.1/torch-2.5.1-cp311-cp311-win_amd64.whl" }
ssqueezepy = "*"

[environments]
audio = ["base", "audio"]
arithmetic = ["base", "arithmetic"]
