[project]
name = "glatzel-bench"
channels = ["conda-forge", "pytorch", "nvidia"]
platforms = ["win-64"]
authors = ["Glatzel <893016099@qq.com>"]
[feature.base.dependencies]
python = "3.11.*"
numpy = "1.24.*"
pytest = "*"
pytest-benchmark = "*"
pytest-cov = "*"

[feature.audio.dependencies]
librosa = "*"
numba = ">=0.60.0"
pyfftw = "*"
pygal = "*"
pysoundfile = "*"
pytorch = { version = "*", build = "*cpu*" }
scipy = "*"
torchaudio = "*"
numexpr = "*"

[feature.audio.pypi-dependencies]
audiofile = "*"
ssqueezepy = "*"
[feature.arithmetic.dependencies]
numba = ">=0.60.0"
numexpr = "*"
pyfftw = "*"
pygal = "*"
scipy = "*"
[feature.arithmetic.pypi-dependencies]
ssqueezepy = "*"
[feature.arithmetic-cpu.dependencies]
pytorch = { version = "*", build = "*cpu*" }
[feature.arithmetic-gpu.system-requirements]
cuda = "12.4"

[environments]
audio = ["base", "audio"]
arithmetic-cpu = ["base", "arithmetic", "arithmetic-cpu"]
