[project]
name = "glatzel-bench"
channels = ["conda-forge", "pytorch"]
platforms = ["win-64","linux-64"]
authors = ["Glatzel <893016099@qq.com>"]

[dependencies]
librosa = "*"
numba = ">=0.60.0"
numpy = "1.26.*"
pyfftw = "*"
pygal = "*"
pysoundfile = "*"
pytest = "*"
pytest-benchmark = "*"
pytest-cov = "*"
python = "*"
pytorch = { version = "*", build = "*cpu*" }
scipy = "*"
torchaudio = "*"

[pypi-dependencies]
audiofile = "*"
ssqueezepy = "*"
