name: CI

on:
  push:
    branches: main
    paths-ignore:
      - "scripts/*"
      - "*.md"
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - ready_for_review
    paths-ignore:
      - "scripts/*"
      - "*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cache-pixi:
    # if: ${{github.event_name == 'push'}}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          frozen: true
          environments: >-
            audio
            arithmetic-cpu
          cache: false
          cache-write: false

  ruff-lint:
    uses: Glatzel/template/.github/workflows/ruff.yml@main

  pytest-audio:
    needs: cache-pixi
    if: always()
    uses: Glatzel/template/.github/workflows/pytest.yml@main
    with:
      name: test
      machine: windows-latest
      cache_write: ${{ github.event_name == 'push'}}
      pixi_python_env: audio
      test_path: ./src/audio
      update_submodule: true
      test_args: --benchmark-max-time=0.00005 --benchmark-min-rounds=1 --benchmark-histogram=histogram/audio
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  pytest-arithmetic:
    needs: cache-pixi
    if: always()
    uses: Glatzel/template/.github/workflows/pytest.yml@main
    with:
      name: test
      machine: windows-latest
      cache_write: ${{ github.event_name == 'push'}}
      pixi_python_env: arithmetic-cpu
      test_path: ./src/arithmetic
      update_submodule: true
      test_args: --benchmark-max-time=0.00005 --benchmark-min-rounds=1 --benchmark-histogram=histogram/arithmetic
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
