name: CI

on:
  push:
    branches: main
    paths-ignore:
      - "scripts/*"
      - "*.md"
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - ready_for_review
    paths-ignore:
      - "scripts/*"
      - "*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cache-pixi:
    if: ${{github.event_name== 'push'}}
    uses: Glatzel/template/.github/workflows/cache-pixi.yml@main
    strategy:
      matrix:
        pixi_env: [audio, arithmetic]
    with:
      machine: windows-latest
      pixi_env: ${{ matrix.pixi_env }}

  ruff-lint:
    uses: Glatzel/template/.github/workflows/ruff.yml@main

  pytest:
    needs: cache-pixi
    if: ${{!cancelled()}}
    strategy:
      matrix:
        include:
          - submodule: true
            pixi_python_env: audio
            test_path: ./src/audio
          - submodule: false
            pixi_python_env: arithmetic
            test_path: ./src/arithmetic
    uses: Glatzel/template/.github/workflows/pytest.yml@main
    with:
      name: test
      machine: windows-latest
      pixi_python_env: ${{ matrix.pixi_python_env }}
      test_path: ${{matrix.test_path}}
      update_submodule: ${{matrix.submodule}}
      test_args: --benchmark-max-time=0.00005 --benchmark-min-rounds=1 --benchmark-histogram=histogram
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
