name: CI

on:
  push:
    branches: main
    paths-ignore:
      - "scripts/*"
      - "*.md"
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - ready_for_review
    paths-ignore:
      - "scripts/*"
      - "*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruff-lint:
    uses: Glatzel/template/.github/workflows/lint.yml@main

  pytest-audio:
    uses: Glatzel/template/.github/workflows/pytest.yml@main
    strategy:
      matrix:
        os: [windows-latest]
    with:
      name: test
      machine: ${{matrix.os}}
      pixi_python_env: audio
      test_path: ./src/audio
      update_submodule: true
      test_args: --benchmark-max-time=0.00005 --benchmark-min-rounds=1 --benchmark-histogram=histogram/audio
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  pytest-arithmetic:
    uses: Glatzel/template/.github/workflows/pytest.yml@main
    strategy:
      matrix:
        os: [windows-latest]
    with:
      name: test
      machine: ${{matrix.os}}
      pixi_python_env: arithmetic-cpu
      test_path: ./src/arithmetic
      update_submodule: true
      test_args: --benchmark-max-time=0.00005 --benchmark-min-rounds=1 --benchmark-histogram=histogram/arithmetic
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
