name: test
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - ready_for_review

permissions:
  contents: read
  actions: read
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: Glatzel/py-template/.github/workflows/pytest.yml@main
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    with: 
      name: test
      machine: ${{matrix.os}}
      test_path: ./src
      update_submodule: true
      test_args: --benchmark-max-time=0.00005 --benchmark-min-rounds=1 --benchmark-histogram=histogram/audio
      cov: true
